### ISSUE TITLE
WPF view MainWindow.xaml

### ISSUE THREAD

**Issue by VicLo2020** [punker76/simple-music-player#58]
Hello!

VisualStudio 2019

Viewing MainWindow.xaml in the constructor throws an error:
InvalidCastException: Could not cast object type "System.Object" to type "SimpleMusicPlayer.ViewModels.PlayControlViewModel".

What could it be?

**Comment by punker76** [comment]
@VicLo2020 I have no idea. Do you have a stack trace? Which Visual Studio version are you using?

**Comment by punker76** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue with the latest code.

Thank you! 🙏
